server:
  port: 6001

spring:
  application:
    name: oauth
  datasource:
    url: jdbc:mysql://1.1.1.1:3306/credentials?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: "11111@，3#￥%11"
    driver-class-name: com.mysql.cj.jdbc.Driver

debug: true

mybatis:
  type-aliases-package: com.softmax.oauth2.security.user
  mapper-locations:  classpath:mapper/*Mapper.xml

