#server:
#  port: 6001
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  application:
#    name: oauth
#  datasource:
#    url: jdbc:mysql://10.10.10.250:3306/credentials?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: "000003"
#    driver-class-name: com.mysql.cj.jdbc.Driver

#debug: true

mybatis:
  type-aliases-package: com.softmax.oauth2.security.user.entity
  mapper-locations:  classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

server:
  port: 6001

# 数据分片+读写分离
sharding:
  datasource:
    # 第一个master
    credentials0:
      alias: ds_master0
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials0?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      #      url: jdbc:mysql://10.10.10.250:3306/credentials?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
    credentials2:
      alias: ds_master0_slave0
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials2?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
    credentials3:
      alias: ds_master0_slave1
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials3?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
    # 第二个master
    credentials1:
      alias: ds_master1
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials1?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
    credentials4:
      alias: ds_master1_slave0
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials4?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
    credentials5:
      alias: ds_master1_slave1
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.10.10.250:3306/credentials5?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: "000003"
  shardingRule:
    tables:
      t_order:
        actualDataNodes: ds_ms${0..1}.t_order${0..1}
        # 分库策略 根据user_id取模分库
        databaseStrategy:
          inline:
            shardingColumn: user_id
            algorithmExpression: ds_ms${user_id % 2}
        # 分表策略 根据order_id 取模分表
        tableStrategy:
          inline:
            shardingColumn: order_id
            algorithmExpression: t_order${order_id % 2}
      t_order_item:
        actualDataNodes: ds_ms${0..1}.t_order_item${0..1}
        # 分库策略 根据user_id取模确定数据进哪个数据库
        databaseStrategy:
          inline:
            shardingColumn: user_id
            algorithmExpression: ds_ms${user_id % 2}
        # 分表策略 根据order_id 取模确定数据进哪个表
        tableStrategy:
          inline:
            shardingColumn: order_id
            algorithmExpression: t_order_item${order_id % 2}

    masterSlaveRules:
      ds_ms0:
        masterDataSourceName: credentials0
        slaveDataSourceNames:
          - credentials2
          - credentials3
        loadBalanceAlgorithmType: ROUND_ROBIN
      ds_ms1:
        masterDataSourceName: credentials1
        slaveDataSourceNames:
          - credentials4
          - credentials5
        loadBalanceAlgorithmType: ROUND_ROBIN

    defaultDataSourceName: credentials0




